---
title: "AN597-Week-2"
output: html_document
---

# Coding Challenges for Module 4
install.packages("stringr")

### CHALLENGE 1
```{r}
# Creating a 1 word character vector from the first line in Ulysses
my_charvect<- c("Stately,", "plump", "Buck", "Mulligan", "came", "from", "the", "stairhead,", "bearing", "a", "bowl", "of", "lather", "on", "which", "a", "mirror", "and", "a", "razor", "lay", "crossed")
my_charvect

#Tried this... but "from" must be a finate number NOT a character
my_charvect[seq(from = "Stately", to = "crossed", by = 3)]

## PERSONAL DIFFICULTY 1:
  #I couldn't think of one command to use to pull every 3rd word so I decided to create a matrix with every 3rd word in the 3rd column... see below
#Creating a character matrix with 3 columns so that I can only look at the 3rd column for all the third words; making byrow= TRUE so that the words go in order across the rows
my_charvect_matrix <- matrix(data= my_charvect, nrow=8,ncol=3, byrow = TRUE)
my_charvect_matrix

# extracting only the words in column 3 (all rows) in order to see the third words in the vector
thirdword <- my_charvect_matrix[1:7, 3]
thirdword

#This command also works but I don't want to use it becuase it includes all of the rows; R has repeated the character vector again in order to fill up the entire row (ex: "plump" is repeated using this code)
x2<- my_charvect_matrix[,3]
```


### CHALLENGE 2
```{r}
m <- matrix(data=1:80,nrow=8,ncol=10,byrow=FALSE)
m

#extracting the 2nd, 3rd, and 6th columns
## PERSONAL DIFFICULTY 2:
  #this one gave me some trouble: I tried x<- m[,(2,3,6)], x<- m[,2,3,6], x<- m[,2], m[,3], m[,6], and x<- m[1:8,2] m[1:8,3] m[1:8,6] before I realized I needed to use c()
x<- m[,c(2,3,6)]
x

#extracting the 6th-8th row
x<- m[6:8,]
x

#extracting the elements from row 2, column 2 to row 6, column 9
x<- m[2,2]:m[6,9]
x
```


### CHALLENGE 3
```{r}
#Constructing a 4-dimensional, 400 element array
## PERSONAL DIFFICULTY 3:
  #I was stuck on this one for a bit because I didn't know if you could have 4 numbers inside the c(). In the example on the module, it stated that the code is dim=c(#rows, #cols, #levels)... so what the 4th number denoting? (still confused)
a <- array(data=400:1, dim=c(5,5,4,4))
a
a[1, 1, 1, 2]     #this = 300
a[2, 3, 2, ]      #this = 364 264 164  64
a[1:5, 1:5, 3, 3]    
#this =     
      [,1] [,2] [,3] [,4] [,5]
[1,]  150  145  140  135  130
[2,]  149  144  139  134  129
[3,]  148  143  138  133  128
[4,]  147  142  137  132  127
[5,]  146  141  136  131  126
```

```{r}
#Overwriting
#makes the value of m[7,1] labeled 564
m[7,1] <- 564
#makes all of the numbers in column 8 = 2
m[,8] <- 2
#makes all of the numbers within those rows/columns = 1
m[2:5,4:8] <- 1
#makes all of the numbers within those rows/colums = 20,19,18,17 by row
m[2:5,4:8] <- c(20,19,18,17)
#created a matrix using 20:1 descending by row
m[2:5,4:8] <- matrix(data = c(20:1), nrow=4,ncol=5,byrow=TRUE)
#makes column 8 go back to "a", "b" values 
m[,8] <- c("a","b")
```

```{r}
#Lists and Data Frames: copying these codes from the module just to practice
s <- c("this","is","a","vector","of","strings")
m <- matrix(data=1:40, nrow=5, ncol=8)
b<- FALSE
l <- list(s, m, b)
#to access an element within the list use double brackets
l[[2]]
# to access elements within an element in the list
l[[2]][2,6]
#To reference/extract multiple elements from a list, you would use single bracket notation, which would itself return a list. This is called “list slicing”
l[1:2]
l[c(1,3)]
#use str() to provide details about the three elements
str(l)
#adding names to the elements within the list
names(l) <- c("string", "matrix", "logical")
names(l)
#use the name of the element to refer to it specifically
l$string
l$matrix[3,5]
```

### CHALLENGE 4
```{r}
#Create a list representing the primate taxonomy
#I created lists for some of the subgroups so that I could use these lists as "elements" in my main list ("full_tax")
Platyrrhini<- list("Cebidae", "Atelidae", "Pitheciidae")
Catarrhini<- list("Cercopithecidae", "Hylobatidae", "Hominidae")
Lorisoidea<- list("Lorisidae", "Galagidae")
Lemuroidae<- list("Cheriogalaedae", "Lepilemuridae", "Indriidae", "Lemuridae", "Daubentoniidae")

## PERSONAL DIFFICULTY 4:
  #I wasn't sure the best way to do this was. I knew from his "hint" that we should have lists as elements in other lists so I did that for a few of the subgroups but not all. Is there a way to display it so that it indents as you move down the groups (as seen in the module?). 
#My full taxonomy List: Any element that does NOT have "" is a pre-made list from up above
Full_tax<- list("Primates", "Haplorhini", "Anthropoidea", "Platyrrhini", Platyrrhini, "Catarrhini", Catarrhini, "Tarsioidea", "Tarsiidae", "Strepsirhini", "Lorisoidea", Lorisoidea, "Lemuroidae", Lemuroidae)
Full_tax

#This is what Full_tax looks like 
[[1]]
[1] "Primates"

[[2]]
[1] "Haplorhini"

[[3]]
[1] "Anthropoidea"

[[4]]
[1] "Platyrrhini"

[[5]]
[[5]][[1]]
[1] "Cebidae"

[[5]][[2]]
[1] "Atelidae"

[[5]][[3]]
[1] "Pitheciidae"


[[6]]
[1] "Catarrhini"

[[7]]
[[7]][[1]]
[1] "Cercopithecidae"

[[7]][[2]]
[1] "Hylobatidae"

[[7]][[3]]
[1] "Hominidae"


[[8]]
[1] "Tarsioidea"

[[9]]
[1] "Tarsiidae"

[[10]]
[1] "Strepsirhini"

[[11]]
[1] "Lorisoidea"

[[12]]
[[12]][[1]]
[1] "Lorisidae"

[[12]][[2]]
[1] "Galagidae"


[[13]]
[1] "Lemuroidae"

[[14]]
[[14]][[1]]
[1] "Cheriogalaedae"

[[14]][[2]]
[1] "Lepilemuridae"

[[14]][[3]]
[1] "Indriidae"

[[14]][[4]]
[1] "Lemuridae"

[[14]][[5]]
[1] "Daubentoniidae"
```

```{r}
#Creating a data frame from scratch
df <- data.frame(firstName=c("Nitin","Silvy","Ingrid","Claire"), program=c("iSchool","Anthro","Anthro","EEB"), sex=c("M","F","F","F"), yearInProgram=c(1,2,2,3))
df

#using a saved document to create a data frame
df <- read.csv("random-people.csv", sep =",", header = TRUE, stringsAsFactors = FALSE)
df[,c(1,3,4,11,12)]
str(df)
df[,3]
str(df[,3])
df$name.last
str(df$name.last)
df[3]
str(df[3])
df["name.last"]
str(df["name.last"])

#adding additional rows and columns
df <- cbind(df, id=c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20))
df <- cbind(df, school=c("BU","BU","Harvard","Harvard","BU","Boston College","MIT","BU","BU","UMASS Boston","Harvard","BU","Boston College","BU","Harvard","MIT","Harvard","BU", "UMASS Boston", "Harvard"))
df

#OR you could extend a data frame by adding a new variable using the $ key
df$school <- c("BU","BU","Harvard","Harvard","BU","Boston College","MIT","BU","BU","UMASS Boston","Harvard","BU","Boston College","BU","Harvard","MIT","Harvard","BU", "UMASS Boston", "Harvard")
#NOTE: cbind() results in school being added as a factor while using the $ operator results in school being added as a character vector. You can see this by using the str() command.

#Filtering out subsets
new_df <- df[df$school == "BU",]
new_df <- df[df$school == "BU", c("name.last", "name.first", "school")]
```


### CHALLENGE 5
```{r}
#create a new 5x3 matrix
## PERSONAL DIFFICULTY 5:
  # I didn't know if 5x3 matrix means rows=5, cols=3 OR rows=3, cols=5.. so I decided to just go with rows=3, cols=5
new_matrix<- matrix(data= c(3,0,1,23,1,2,33,1,1,42,0,1,41,0,2), nrow=3, ncol=5, byrow = TRUE)
new_matrix

#Coerce the matrix to a data frame
data_frame<- data.frame(new_matrix)
data_frame

#show only column 2
data_frame$X2
# NOTE: data_frame[X2] does NOT work because we didn't name column 2

#coerce column 2 to be logical-valued
col2<- as.logical(data_frame$X2)
col2
str(col2) #this shows that its logical-valued

#coerce column 3 to be factor-valued
col3<- as.factor(data_frame$X3)
col3
str(col3) #this shows that its factor-valued
```

### THE END
